packages:
  - packages/*
  - playground
  - docs

catalogs:
  dev:
    typescript: ~5.9.3
    tsdown: ~0.21.0-beta.2
    publint: ^0.3.17
  types:
    '@types/node': ^25.3.0

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade
