packages:
  - packages/*
  - playground
  - docs

catalogs:
  dev:
    typescript: ~5.9.3
    tsdown: ^0.21.4
    publint: ^0.3.17
    vite: ^8.0.2
    vitest: ^4.1.0
    solid-js: ^1.9.11
    less: ^4.6.4
    rolldown-plugin-solid: ^0.2.1
    vite-plugin-solid: ^2.11.11
  prod:
    clsx: ^2.1.1
  types:
    '@types/node': ^25.3.0

cleanupUnusedCatalogs: true

shellEmulator: true

# trustPolicy: no-downgrade
